
x-app-env: &app_env
  # Default to HOST ollama; change to http://ollama:11434 when using dockerized Ollama
  OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
  MODEL: ${MODEL:-llama3.1:8b}
  EMBED_MODEL: ${EMBED_MODEL:-nomic-embed-text}
  SERPER_API_KEY: ${SERPER_API_KEY}
  MAX_STEPS: ${MAX_STEPS:-8}
  TEMPERATURE: ${TEMPERATURE:-0.2}
  MEMORY_BACKEND: ${MEMORY_BACKEND:-pgvector}
  SQLITE_PATH: ${SQLITE_PATH:-/app/.data/agent.db}  # kept for optional sqlite demos
  PGHOST: ${PGHOST:-pgvector}
  PGPORT: ${PGPORT:-5432}
  PGUSER: ${PGUSER:-agent}
  PGPASSWORD: ${PGPASSWORD:-agent}
  PGDATABASE: ${PGDATABASE:-agentdb}

services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: py-basic-agent-pgvector-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  # One-shot: ensure role/db exist even on an existing volume
  db-bootstrap:
    image: postgres:16
    depends_on:
      pgvector:
        condition: service_healthy
    environment:
      PGPASSWORD: postgres
    command: >
      sh -lc "psql -h pgvector -U postgres -v ON_ERROR_STOP=1 -f /bootstrap.sql"
    volumes:
      - ./app/db/bootstrap.sql:/bootstrap.sql:ro
    restart: "no"

  # One-shot: apply schema to agentdb (idempotent, runs as agent)
  db-setup:
    image: postgres:16
    depends_on:
      pgvector:
        condition: service_healthy
    environment:
      PGPASSWORD: agentpass
    command: >
      sh -lc "psql -h pgvector -U agent -d agentdb -v ON_ERROR_STOP=1 -f /schema.sql"
    volumes:
      - ./app/db/schema.sql:/schema.sql:ro
    restart: "no"

  # App runs by default and can reach host's Ollama (Mac & Linux)
  app:
    build:
      context: ./app
    stdin_open: true
    tty: true
    env_file: .env
    environment:
      <<: *app_env
      PYTHONPATH: /app
      # Safe defaults; can be overridden in .env
      AGENT_DB_URL: ${AGENT_DB_URL:-postgresql://agent:agentpass@pgvector:5432/agentdb}
      OLLAMA_HOST: ${OLLAMA_HOST:-http://host.docker.internal:11434}
      AGENT_EMBED_MODEL: ${AGENT_EMBED_MODEL:-nomic-embed-text}
      AGENT_EMBED_DIM: ${AGENT_EMBED_DIM:-768}
    volumes:
      - ./app:/app
      - ./data:/app/data:rw
      - ./.data:/app/.data:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      pgvector:
        condition: service_healthy
      db-bootstrap:                # one-shot: creates role/db if missing
        condition: service_completed_successfully
      db-setup:                    # one-shot: applies schema.sql (idempotent)
        condition: service_completed_successfully
      mcpfs:
        condition: service_started
  
  test:
    build: .
    env_file: .env
    volumes:
      - .:/app
    entrypoint: pytest
    command: -q
    depends_on:
      pgvector:
        condition: service_healthy
      mcpfs:
        condition: service_started
  
  mcpfs:
    image: node:20-alpine
    working_dir: /srv
    environment:
      FS_MCP_ROOT: /app/data
      PORT: 8765
      ENABLE_STDIO: "0"
    volumes:
      - ./servers/fs-mcp-server:/srv
      - ./data:/app/data:rw
    command: sh -lc "npm i --omit=dev && node index.js"
    ports:
      - "8765:8765"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:8765/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  # Optional: dockerized Ollama, only when you enable the profile
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   profiles: ["ollama-docker"]
  #   ports: ["11434:11434"]
  #   volumes:
  #     - ollama:/root/.ollama
  #   healthcheck:
  #     test: ["CMD", "curl", "-sf", "http://localhost:11434/api/tags"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 20
  #   entrypoint:
  #     - /bin/sh
  #     - -lc
  #     - |
  #       ollama serve & sleep 2
  #       ollama pull ${MODEL:-llama3.1:8b}
  #       ollama pull ${EMBED_MODEL:-nomic-embed-text}
  #       tail -f /dev/null

volumes:
  pgdata: {}
  # ollama:
